services:
  - type: web
    name: instagram-agent-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
      playwright install-deps chromium
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    disk:
      name: insta-session-data
      mountPath: /app/user_data_dir
      sizeGB: 1
    envVars:
      - key: INSTA_USER
        value: hiiamdudetntt
      - key: INSTA_PASS
        value: ritika123
